apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "sleep 20"]
  containers:
  - name: redis
    image: redis

